import groovy.json.JsonSlurper

val adaptersRoot: File = rootProject.file("packages/wlya-adapters")
val coreGeneratedDir: File = project.layout.buildDirectory.dir("generated/kotlin").get().asFile
val androidModuleDir: File = project.rootProject.file("apps/gateway/app")
val androidGeneratedDir: File = androidModuleDir.resolve("build/generated/kotlin")

fun Any?.toKotlinLiteral(): String = when (this) {
    is String -> "\"" + this.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
    is Boolean -> this.toString()
    is Number -> this.toString()
    null -> "null"
    else -> "\"" + this.toString().replace("\"", "\\\"") + "\""
}

fun Map<*, *>.toKotlinMapLiteral(): String {
    if (isEmpty()) return "emptyMap()"
    return "mapOf(\n" + entries.joinToString(",\n") { (k, v) ->
        "                \"$k\" to ${v.toKotlinLiteral()}"
    } + "\n            )"
}

tasks.register("generateAdapterRegistries") {
    inputs.dir(adaptersRoot)
    outputs.dir(coreGeneratedDir)
    outputs.dir(androidGeneratedDir)

    doLast {
        val slurper = JsonSlurper()
        val adapterDirs = adaptersRoot.listFiles()
            ?.filter { it.isDirectory && it.resolve("adapter.json").exists() }
            ?.sortedBy { it.name }
            ?: emptyList()

        val registrations = mutableListOf<String>()
        val androidEntries = mutableListOf<Pair<String, String>>()

        for (dir in adapterDirs) {
            val meta = slurper.parse(dir.resolve("adapter.json")) as Map<String, Any>
            val type = meta["type"] as String
            val label = meta["label"] as String
            val adapterClass = meta["adapterClass"] as String
            val factoryKind = meta["factoryKind"] as? String ?: "simple"
            val defaultConfig = meta["defaultConfig"] as? Map<*, *> ?: emptyMap<String, Any>()

            val factoryBody = when (factoryKind) {
                "mock" -> """
                val id = config["id"] as? String ?: "default"
                val storePath = config["storePath"] as? String ?: ".wlya/local-store.json"
                MockAdapter(id, LocalStore(storePath))
                """.trimIndent()
                else -> """
                val id = config["id"] as? String ?: "default"
                $adapterClass(id, config)
                """.trimIndent()
            }

            registrations.add(
                """
        Registry.register(
            AdapterManifest(
                type = "$type",
                label = "$label",
                defaultConfig = ${defaultConfig.toKotlinMapLiteral()},
                factory = { config ->
                    $factoryBody
                },
            )
        )
                """.trimIndent()
            )

            val androidDir = dir.resolve("ui-android")
            // Phone Settings: skip mock; email, wlyaserver, and any future types are included.
            if (androidDir.exists() && type != "mock") {
                androidDir.listFiles()
                    ?.filter { it.name.endsWith("AdapterForm.kt") }
                    ?.forEach { formFile ->
                        val className = formFile.nameWithoutExtension
                        val packageName = "com.wlya.core.adapters.${dir.name}.ui.android"
                        androidEntries.add(type to "$packageName.$className")
                    }
            }
        }

        val coreOut = coreGeneratedDir.resolve("com/wlya/core/adapters/GeneratedAdapterRegistry.kt")
        coreOut.parentFile.mkdirs()
        coreOut.writeText(
            """
package com.wlya.core.adapters

/** Generated by generateAdapterRegistries — do not edit. */
fun registerAllAdapters() {
${registrations.joinToString("\n\n")}
}
            """.trimIndent() + "\n"
        )

        val androidOut = androidGeneratedDir.resolve("com/wlya/adapters/ui/GeneratedAndroidFormRegistry.kt")
        androidOut.parentFile.mkdirs()
        val imports = androidEntries.map { it.second }.distinct().sorted()
        val mapEntries = androidEntries.joinToString(",\n") { (type, fqcn) ->
            val simple = fqcn.substringAfterLast('.')
            "        \"$type\" to $simple()"
        }

        androidOut.writeText(
            """
package com.wlya.adapters.ui

${imports.joinToString("\n") { "import $it" }}

/** Generated by generateAdapterRegistries — do not edit. */
object GeneratedAndroidFormRegistry {
    private val forms: Map<String, AdapterAndroidForm> = mapOf(
$mapEntries
    )

    fun get(type: String): AdapterAndroidForm? = forms[type]

    fun listTypes(): List<String> = forms.keys.sorted()

    fun labels(): Map<String, String> = mapOf(
${adapterDirs.filter { dir ->
    val meta = slurper.parse(dir.resolve("adapter.json")) as Map<String, Any>
    meta["type"] != "mock"
}.joinToString(",\n") { dir ->
    val meta = slurper.parse(dir.resolve("adapter.json")) as Map<String, Any>
    "        \"${meta["type"]}\" to \"${meta["label"]}\""
}}
    )
}
            """.trimIndent() + "\n"
        )
    }
}

tasks.named("compileKotlin") {
    dependsOn("generateAdapterRegistries")
}
